# Generated by Django 2.1.5 on 2019-02-13 05:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('isEvent', models.BooleanField(default=False)),
                ('eventDate', models.DateField()),
                ('eventTimeFrom', models.TimeField()),
                ('eventTimeTo', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apptDate', models.DateField()),
                ('apptTimeFrom', models.TimeField()),
                ('apptTimeTo', models.TimeField()),
                ('apptDescription', models.CharField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 2, 13, 5, 24, 59, 944475, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentBy', models.CharField(max_length=50)),
                ('commentDate', models.DateField(default=datetime.datetime(2019, 2, 13, 5, 24, 59, 942923, tzinfo=utc))),
                ('commentTime', models.TimeField(default=datetime.datetime(2019, 2, 13, 5, 24, 59, 942975, tzinfo=utc))),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateField()),
                ('timeFrom', models.TimeField()),
                ('timeTo', models.TimeField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventPlanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=20)),
                ('relation', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother')], max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCardPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_type', models.CharField(max_length=20)),
                ('exam_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('acknowledgement', models.BooleanField(default=False)),
                ('reportCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ReportCard')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=20)),
                ('form_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nric', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('child_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ParentProfile')),
                ('form_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Class')),
            ],
        ),
        migrations.CreateModel(
            name='StudentToSubjectClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('classOf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Class')),
                ('student', models.ManyToManyField(through='main.StudentToSubjectClass', to='main.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50)),
                ('marks', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reportCardPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ReportCardPage')),
            ],
        ),
        migrations.AddField(
            model_name='studenttosubjectclass',
            name='subjectClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SubjectClass'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventPlanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EventPlanner'),
        ),
        migrations.AddField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='eventPlanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EventPlanner'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ParentProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='studenttosubjectclass',
            unique_together={('subjectClass', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
