# Generated by Django 2.1.7 on 2019-03-06 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190306_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appTitle',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 11, 15, 58, 846689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 11, 15, 58, 846689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.TimeField(default=datetime.datetime(2019, 3, 6, 11, 15, 58, 846689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
