# Generated by Django 2.1.7 on 2019-03-06 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190306_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appTitle',
            new_name='apptTitle',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 11, 51, 11, 486312, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 11, 51, 11, 486312, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.TimeField(default=datetime.datetime(2019, 3, 6, 11, 51, 11, 486312, tzinfo=utc)),
        ),
    ]
