# Generated by Django 2.1.5 on 2019-03-08 01:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190306_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apptLocation',
            field=models.CharField(default='General Office', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 8, 1, 29, 14, 753506, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 8, 1, 29, 14, 752509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.TimeField(default=datetime.datetime(2019, 3, 8, 1, 29, 14, 752509, tzinfo=utc)),
        ),
    ]
