# Generated by Django 2.1.5 on 2019-03-08 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190308_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apptRejectionReaseaon',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='apptStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 8, 7, 23, 9, 374002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 8, 7, 23, 9, 374002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.TimeField(default=datetime.datetime(2019, 3, 8, 7, 23, 9, 374002, tzinfo=utc)),
        ),
    ]
