# Generated by Django 2.1.5 on 2019-03-08 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190308_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='apptRejectionReaseaon',
            new_name='apptRejectionReason',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 8, 7, 56, 59, 920052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(default=datetime.datetime(2019, 3, 8, 7, 56, 59, 920052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.TimeField(default=datetime.datetime(2019, 3, 8, 7, 56, 59, 920052, tzinfo=utc)),
        ),
    ]
